version: '3'
services:

# Servidor Web 01
  web01:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: web01
    container_name: web01
    restart: always
    tty: true
    networks:
      - asa-network

# Servidor Web 02
  web02:
    build:
      context: ./web
      dockerfile: Dockerfile.web2
    image: web02
    container_name: web02
    restart: always
    tty: true
    networks:
      - asa-network
      
# Servidor de proxy
  proxy:
    build:
      context: ./web
      dockerfile: Dockerfile.proxy
    image: proxy
    container_name: proxy
    hostname: www.am.asa.br
    restart: always
    tty: true
    ports:
      - "80:80"
    depends_on:
      - web01
      - web02
    networks:
      - asa-network

# Servidor de DNS
  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    image: dns
    container_name: dns
    hostname: ns1.am.asa.br
    restart: always
    tty: true
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./dns/etc:/etc/bind
    networks:
      - asa-network
 
 # Servidor de Email
  mail:
    build:
      context: ./email
      dockerfile: Dockerfile
    image: email
    container_name: email
    hostname: mail.am.asa.br
    restart: always
    tty: true
    ports:
      - "25:25/tcp"
      - "587:587/tcp"
      - "143:143/tcp"
    networks:
      - asa-network

# Identificando Redes
networks:
  asa-network:
    driver: bridge

